### ISSUE TITLE
Feature request: Lumina-config to remember window size

### ISSUE THREAD

**Issue by q-pa** [lumina-desktop/lumina#530]
It is a bit annoying that lumina-config does not remember the window size even when switching between menus. What makes it worse, the default window is way to small. This is not priority 1, of course, but maybe with some update...

**Comment by q5sys** [comment]
Thanks for the request!  We'll talk it over and add it to the list if it's something we think we should implement.

**Comment by beanpole135** [comment]
Fixed.
https://github.com/lumina-desktop/lumina/commit/d36a94b449cb09d91827347b3ef2933bda50d1c0
