### ISSUE TITLE
Bug: lumina-fm -  Some file operations disabled when dir list loses focus for View Change

### ISSUE THREAD

**Issue by kbartosik** [lumina-desktop/lumina#549]
**Lumina version**: 1.4.1
**OS**: FreeBSD 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Symptoms**: some file operations (Del, Cut, Paste, Copy) are made inaccessible after user changes View.
**Steps to reproduce:** Open Insight (in Home dir), left click on file you have full access to - this should show all operations are allowed in pop-u menu. Then select View->Change View, select basic and then without leaving menu select back to extended. As the result the file list remains unchanged, but some operations are no longer allowed.  This might be due to folder list on the left hand side loses focus and for some reason shows that root folder (/) is selected
(sorry if I am not putting the proper names for actions as I am using <partially> translated version).

**Comment by q5sys** [comment]
Thanks for the report.  We'll look into this.

**Comment by RJules3** [comment]
**Lumina version:** 1.4.2_201803131031,3
**OS:** FreeBSD trueos-25 12.0-CURRENT FreeBSD 12.0-CURRENT #26 fa797a5a3(trueos-stable-18.03): Mon Mar 26 00:24:47 UTC 2018     root@chimera:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

**Symptoms:** Refreshing (via menu 'View -> Refresh' or function key F5) a view in 'Insight' leads to the same symptom as above described by @kbartosik plus the highlighting within the tree pane is removed and the field of the path is emptied. The view of the content of a folder is not refreshed. Two pictures one can see in this [discourse.trueos thread](https://discourse.trueos.org/t/lumina-file-manager-insight-doesnt-refresh-via-menu-or-f5/2890).
**Steps to reproduce:** Open Insight in any folder. Path field is populated and tree is highlighted. Push F5 or choose View -> Refresh. The highlighting is removed, the path field is emptied, and the context menu of any content within the chosen folder is very limited.

**Comment by q5sys** [comment]
Thanks for the reports. I've been able to confirm both of these behaviors.  We'll try to get them fixed as soon as we can, but we've got a lot on our plate right now.
