### ISSUE TITLE
Power Off not working

### ISSUE THREAD

**Issue by acooper306** [lumina-desktop/lumina#559]
when I select "leave" from the menu, and then select "power off", all it does it log me out.  It doesn't power off the machine.

I'm using a dell latitude e7250

**Comment by beanpole135** [comment]
Please check whether the setuid bit is available on the /sbin/shutdown binary, and if so what permissions are available:
` ls -l /sbin/shutdown`

What you should see is something like this:
```
[kenmoore@WorkWraith] ~% ls -l /sbin/shutdown 
-r-sr-xr--  2 root  operator  23096 Mar 23 09:54 /sbin/shutdown
```
That allows users in the "operator" group to be able to shutdown the system. There was a bug with FreeBSD about a month ago where that setuid bit was getting removed from the shutdown binary, but if you have done an update recently that should already be fixed.

**Comment by acooper306** [comment]
Here is what I got, it looks about the same as what you had, except for the
date.

-r-sr-xr--  2 root  operator  15432 Dec  9 10:34 /sbin/shutdown

It is still just logging me out and taking back to the graphical login
screen.
