### ISSUE TITLE
Missing sound volume icon

### ISSUE THREAD

**Issue by samob** [lumina-desktop/lumina#562]
I have latest unstable installed from scratch:
```
===================
General information
===================

boot environment now (N) … initial NR 2018-03-25
       after restart (R) … initial NR 2018-03-25
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    number of cores ……………… 8
host ……………………………………………………… trueos.rula.org
memory ………………………………………………… 16384 MB available, 10803 MB free
OS git branch ……………………………………………………………………………………… trueos-master
OS git revision ………………………………………………………………………………… 072ecd92c
OS kernel build time ………………………………………………………… Fri 2018 Mar 16 18:11:44 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201803131015
uptime ………………………………………………… 1:35
user  …………………………………………………… samob

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <Realtek ALC1150 (Rear Analog 5.1/2.0)> (play/rec) default
    wireless driver ……………… 
    X11 drivers ………………………… nvidia_drv.so
``` 
The tray icon for sound volume is missing. Sound is working fine, and I can start it via Utility - TrueOS mixer tray, but I believe it should be started automatically? 
I went to Service manager and enabled automatic start on boot for mixer, but nothing changed:
![mixer-enabled](https://user-images.githubusercontent.com/335163/38190717-cd3c9260-3665-11e8-8705-8499ddb990ba.png)

**Comment by q5sys** [comment]
Check something for me.  Open `lumina-config` and go to the page for startup applications.  Check to see if Mixer is listed there.  If its not, add it.  If its listed but not enabled, enable it.  Then try a reboot and see if it shows up.

The Service Manager in sysadm enables the service, the panel widget still needs to be autostarted by Lumina.

**Comment by samob** [comment]
Yes, mixer command was missing and after adding it all is well
