### ISSUE TITLE
lumina-open should exit after detach

### ISSUE THREAD

**Issue by rodlie** [lumina-desktop/lumina#577]
Hi, why is lumina-open still running after detaching the requested process?

**Comment by q5sys** [comment]
I asked Ken about this two years ago, and if memory serves his answer was that It stays running so that it can monitor the process and report back any issues.  Basically this was an intentional design decision.  It's not documented though, so we get the question every now and again.

**Comment by rodlie** [comment]
Ahh, ok I thought maybe this was an bug. Thanks for the info :)

**Comment by beanpole135** [comment]
@q5sys is correct, the default behavior will keep track of the process and popup a crash dialog if it exits erratically. Even though the overhead for this monitoring is really trivial, you can still disable it within the "User Settings" page of lumina-config if you like (the "Show application crash data" option).
