### ISSUE TITLE
Issues with multiple screens

### ISSUE THREAD

**Issue by rodlie** [lumina-desktop/lumina#586]
So,

Connected an external monitor to my laptop and booted the machine with the lid down.

The laptop monitor is 720p and the external monitor is 1920x1200.

The first I noticed was that the boot splash was centered in 720p in the top left corner on the external screen.

Then I was greeted with:
![lumina-broken-multiscreen](https://user-images.githubusercontent.com/34516798/40065286-bd158fe0-5861-11e8-8d74-95e1bc198894.png)

So the panel from my (disabled) laptop screen is showing... And is primary (see systray).

Then I opened the X settings and selected my external monitor as primary and logged out...
![lumina-broken-multiscreen2](https://user-images.githubusercontent.com/34516798/40065402-09969396-5862-11e8-9d09-8edf6013148b.png)

And then logged in again and this happened:
![lumina-broken-multiscreen3-primary](https://user-images.githubusercontent.com/34516798/40065439-1a11afc6-5862-11e8-8039-fec3aa41c753.png)

... So my complete desktop from the laptop screen is included(!), but systray items are now on my primary panel, and the boot splash was centered.

It also seems like auto-started applications are started twice, not sure. The screensaver flashes two times and locks the screen at startup also.

**Comment by q5sys** [comment]
In the xsettings make sure that the laptop screen window is not hiding below the external window.  I use my laptop with two external screens and have never had an issue.

**Comment by q5sys** [comment]
To clarify further, I've never had this happen unless the screen windows in the xsettings util are overlapping in some way.

**Comment by rodlie** [comment]
Currently not running Lumina, but the issue is that the internal screen is on in xrandr.

So, Lumina/xsettings should know that my internal screen is off and don't use it.

**Comment by rodlie** [comment]
So... Was about to start debugging this issue, but encountered another issue (of course).

* Start lumina
* in a terminal turn off laptop monitor: ``xrandr --output LVDS1 --off``
* Now turn it on: ``xrandr --output LVDS1 --auto`` (any option that turn it on).
* The panel has now moved to the top, and all open applications are missing window border, and the DPI is wacky
![screenshot-2018-05-23-14-39-46](https://user-images.githubusercontent.com/34516798/40425116-baaf6f5a-5e97-11e8-9667-0206ecace0b4.png)

Doing the same in Fluxbox/Openbox does not trigger any issues.

**Comment by beanpole135** [comment]
Whenever you manually modify the X session layout, you need to run "killall fluxbox" to reset fluxbox (known issue - Lumina will automatically restart it for you). The current version of Fluxbox goes bonkers when the session changes size out from underneath it and it stops registering/updating the session variables which control boundaries and such.

**Comment by rodlie** [comment]
Nice, that solved the panel issue :) but the DPI issue is a strange one.
![screenshot-2018-05-23-15-01-09](https://user-images.githubusercontent.com/34516798/40425986-309776a2-5e9a-11e8-83f9-0e4e65495fd6.png)

The DPI get larger and larger every time I turn off and on the monitor.

**Comment by rodlie** [comment]
Good news. Seems like most of the issues was related to kernel (drm/intel). 

After replacing Fluxbox with Openbox and a kernel downgrade everything seems stable.
