### ISSUE TITLE
Simple photo viewer

### ISSUE THREAD

**Issue by q5sys** [lumina-desktop/lumina#600]
Write one

**Comment by lbartoletti** [comment]
Nice idea! 
I wanted to make this request before I came across this ticket :wink: 

For information, I started a small photo viewer project. I hope to submit the first version to you within two weeks.

**Comment by beanpole135** [comment]
lumina-photo is currently available in Project Trident 18.12-RELEASE-U1, and buildable for other OS's from the source tree.
