### ISSUE TITLE
Wireless utility needs to allow you to select between multiple wireless devices

### ISSUE THREAD

**Issue by q5sys** [lumina-desktop/lumina#609]
While trying to do some work today in the hospital with my mom, I found that my internal intel wifi nic in my thinkpad didn't have the necessary power to reach a wireless router that I was running in the back of my car in the parking lot that's part of my mobile test rig of Intel NUCs.

Not a problem, I have an external RT3070 USB wifi adapter with db amplifier and yagi antenna.  Hooked it up, create the interface and I then realized that our gui util doesn't have the ability to select between multiple hardware devices. Or... if it does, it's currently not working properly.

This isn't urgent as I can boot into my windows install on my 2nd internal ssd and connect that way, but I figured I'd make a note of it so it's on our radar for the future.

**Comment by beanpole135** [comment]
Unrelated to Lumina.
