### ISSUE TITLE
Chinese input method?

### ISSUE THREAD

**Issue by outpaddling** [lumina-desktop/lumina#610]
Is it possible in Lumina to enable a Chinese input method, where the user types pinyin and a menu of possible Chinese characters appears?  Or should I switch to KDE for now?  Thanks...

**Comment by beanpole135** [comment]
Lumina is completely agnostic about selected input methods.
I would recommend installing/using the "fcitx" utility for on-the-fly switching between various input methods such as pinyin or traditional chinese.

**Comment by outpaddling** [comment]
Note to posterity:

fcitx works very well, but is not well-documented, so I had a hard time tracking down all the pieces needed to get it working.  There's a lot of misinformation out there that makes it look complicated, but it was actually pretty simple to set up on FreeBSD once I filtered out all the noise.

Like so many things I've done with FreeBSD, all the pieces were readily available, it just took some digging to figure out how to put them together in the most elegant way.

Here's what I did:

pkg install zh-CJKUnifonts zh-font-std zh-opendesktop-fonts zh-CNS11643-font \
    zh-kcfonts

pkg install -y fcitx-qt5 zh-fcitx-sunpinyin zh-fcitx-configtool \
    zh-fcitx-libpinyin zh-fcitx-cloudpinyin qt4-qtconfig

libpinyin and sunpinyin provide alternative input methods (different ways of guessing what Chinese character you want when you start typing pinyin).

export GTK_IM_MODULE, etc. in Xsession or other X startup script as described in the fcitx pkg-message (which was the most useful document I found, albeit an incomplete one).

I use xdm + Lumina, so the tail end of my /usr/local/etc/X11/xdm/Xsession looks like this:

[ snip ]
else
        if [ -r "$resources" ]; then
                /usr/local/bin/xrdb -load "$resources"
        fi
        # From fcitx pkg-message
        XMODIFIERS='@im=fcitx'
        GTK_IM_MODULE=fcitx
        GTK3_IM_MODULE=fcitx
        QT4_IM_MODULE=fcitx # Or use qt4-config to change
        export XMODIFIERS GTK_IM_MODULE GTK3_IM_MODULE QT4_IM_MODULE
        exec /usr/local/bin/start-lumina-desktop
fi

Add fcitx to your desktop auto-start via desktop settings or, e.g.

    ln -s /usr/local/share/applications/fcitx.desktop ~/.config/autostart

Log out and log back in.

Right-click fcitx in the tray, select "Configure".

Uncheck "Only Show Current Language".

Add languages from "Available" to "Current".  The LibPinyin and Sunpinyin
options seem to work well.

Right-click the fcitx icon in the tray, select "Restart".

Right-click fcitx in the tray, select "Input Method" and choose your language.

This last step seems to be application specific, i.e. doing this when a Lilyterm is in the foreground will not change the language for Firefox.

The person I set this up for is now happily using FreeBSD + Lumina desktop after years of using only Windows and a little time on a MacBook up until now.
