### ISSUE TITLE
lumina-fm runs high on CPU after a while

### ISSUE THREAD

**Issue by utrenkner** [lumina-desktop/lumina#614]
This happened a couple of times now: The ventilator in my ThinkPad starts working even though I do only casual office stuff. I check ``top`` and see lumina-fm at more than 100% WCPU. Closing lumina-fm stops this, as expected.

This is on a vanilla FreeBSD 11.2-RELEASE with packages from the official quarterly repo, currently running ``lumina-fm-1.4.1``.

Possibly in connection with this: I also notice sometimes, that after a while with an open lumina-fm window, the content of the current directory is not updated anymore, and a refresh does not help. I have to click a different directory and then back to see e.g. new files.

In my daily work, lumina-fm continues to be the weakest part of the Lumina desktop (but maybe because it is the one Lumina app, I use the most often).

**Comment by q5sys** [comment]
Thanks for the bug report.  We'll look into it.  I've been planning a complete overhaul of the file manager as it's the application that I use the most as well.  But sadly a lot of projects have delayed due to TrueOS splitting the desktop off into `Project Trident`.  We're a bit behind on our timeline.

**Comment by beanpole135** [comment]
This appears to be fixed in latests sources.

**Comment by utrenkner** [comment]
That would be awesome! Especially, since I was already sooo close to switching to another desktop because of this behaviour. Just didn't found the time to set up something else. If it is fixed, I could continue using Lumina.

When do you think these changes could appear in the FreeBSD ports tree? @lattera recently mentioned on Twitter that you plan to update the Lumina port in the not so distant future...
