### ISSUE TITLE
Startup performance

### ISSUE THREAD

**Issue by outpaddling** [lumina-desktop/lumina#615]
Very recent versions of Lumina are rather slow to start.  They hang for a while on "Finalizing" and then again with desktop icons partially drawn.  It's not much of a problem on high-end systems, but it can hang here for 30 seconds or more on my netbook.  ( Thinkpad X120e )

I'm running the latest lumina on FreeBSD 10.4, 11.1, and 11.2 amd64.

lumina-1.4.1,3
Name           : lumina
Version        : 1.4.1,3
Installed on   : Tue Dec 26 18:12:34 2017 CST
Origin         : x11/lumina
Architecture   : FreeBSD:11:*

If Lumina 2 will be released shortly, this may not be worth fixing, but it's a nuisance at the moment.

Thanks...

**Comment by q5sys** [comment]
Thanks for the bug report.  We'll look into it.  Lumina 2 has been delayed a bit due to TrueOS splitting the desktop off into `Project Trident`, so we're a bit behind on our timeline.

**Comment by beanpole135** [comment]
This appears to be fixed in the latest sources.

**Comment by outpaddling** [comment]
Thanks much.  By "latest sources" do you mean Lumina 2 or a patch to the 1.x series?

**Comment by beanpole135** [comment]
Latest Lumina 1.x branch from source (1.4.2+)

**Comment by outpaddling** [comment]
Great, I'll report back if there are any more issues after the next pkg upgrade.

Any idea when 2.x will be in ports?

**Comment by beanpole135** [comment]
Not just yet. Still in development. I am going to push 1.5.0 to ports soon-ish though (maybe in another 2 weeks). I am finishing final QA for that version now.

**Comment by outpaddling** [comment]
Great, thanks!
