### ISSUE TITLE
Sync Weblate with lang sources

### ISSUE THREAD

**Issue by p-bo** [lumina-desktop/lumina#617]
Hi,

noticed, that for example (in other components too) in lumina-config sources
https://github.com/lumina-desktop/lumina/blob/master/src-qt5/core-utils/lumina-config/i18n/lumina-config_cs.ts
there are log of unfinished strings, but on weblate
https://weblate.trueos.org/projects/lumina/lumina-config/cs/
there is all done - so repository and weblate are out of sync.
Would it be possible to fix it please?

Thanks :)

**Comment by beanpole135** [comment]
Weblate is no longer provided by TrueOS.

**Comment by p-bo** [comment]
So time to update instructions?
https://github.com/lumina-desktop/lumina#translations
If developers want to have lumina translated, there is needed some tool with low technical barrier for translators...

**Comment by beanpole135** [comment]
Yep - I will clean up that readme. 
Thanks for pointing that out.
We have been talking about a small local-system app to let you perform translations of the *.ts files for Qt really easily. We still need to take some time to write that app though, so it might be a little bit until it is available.

**Comment by p-bo** [comment]
You can use cost less hosting on weblate instance (thus no need to change current workflow), maintained by its developers:
https://weblate.org/en/hosting/free/
