### ISSUE TITLE
[Feature request][Screenshot] Save last selected area

### ISSUE THREAD

**Issue by lbartoletti** [lumina-desktop/lumina#619]
Sometime, when you capture a lot of selected area, you want to keep the same are. Can you provide an option to keep the last selected area when you create a new capture?

**Comment by beanpole135** [comment]
Interesting idea. 
I think this is completely possible by simple saving/reading a QRect (x,y, width, height) from the QSettings file for the app (~/.config/lumina-desktop/lumina-screenshot.conf).

**Comment by q5sys** [comment]
@lbartoletti Are you asking for it to save region when you close the app for the next time you open it?  Or just that there is another button/option to take another screenshot of the region you previously did without closing the program?  Both are possible, just curious which you were thinking of... if not both options.

**Comment by beanpole135** [comment]
I would make a button to either save the previous region or prompt for a region to save as a "profile" or something in the QSettings.
And then add a drop-down of known profiles as an option when taking a screenshot.
