### ISSUE TITLE
Wallpaper picker not working

### ISSUE THREAD

**Issue by revhelix** [lumina-desktop/lumina#621]
When I open the wallpaper chooser, the right panel doesn't respond.
Unable to choose a wallpaper.

**Comment by q5sys** [comment]
Thanks for the ticket,  Are you saying that you do not get the preview of the wallpaper, like is shown in this?
![wallpaper-select](https://user-images.githubusercontent.com/4654247/45034357-4d2eee80-b025-11e8-976c-d9cd58e0ec07.png)

**Comment by revhelix** [comment]
I was expecting when you select a directory that a series of thumbnails would show. 

That seemed the natural flow for me.
