### ISSUE TITLE
Theme environment not set: QT_QPA_PLATFORMTHEME

### ISSUE THREAD

**Issue by hxw** [lumina-desktop/lumina#623]
While trying to get High DPI screen to show reasonable size fonts I finally discovered that I need to set the environment to run QT app for the theme to take effect otherwise fonts are extremely small; even in lumina-config itself
e.g.:
```
env QT_QPA_PLATFORMTHEME=lthemeengine phototonic
env QT_QPA_PLATFORMTHEME=lthemeengine lumina-config
```

There is a variable: `QP_QPA_PLATFORMTHEME` in the environment, is this a misspelling? or just something for lumina specific apps?

The QP_ variant might just be part of the session handling, because I can see several instances of setting the QT_ version in other source files, but so far I have not determined what conditions case it to be set.

This is on a plain FreeBSD 11.2 system on a T580

**Comment by beanpole135** [comment]
Which version of Lumina are you using?
Lumina automatically sets the QT_QPA_PLATFORMTHEME=lthemeengine environment variable *before* starting the window manager or desktop session.
It is possible that you are using an old build of Lumina *or* you have a mis-typed environment variable override within your ~/.config/lumina-desktop/envsettings.conf file.

**Comment by hxw** [comment]
~~~
% uname -r
11.2-RELEASE-p3

% pkg info |grep lumina
lumina-1.4.1,3                 Lumina Desktop Environment (meta-port)
lumina-archiver-1.4.1          Archive manager from the Lumina Desktop
lumina-calculator-1.4.1        Scientific calculator from the Lumina Desktop
lumina-core-1.4.2_201803131031 Lumina Desktop Environment
lumina-coreutils-1.4.1         Lumina Desktop Environment
lumina-fileinfo-1.4.1_1        File properties utility from the Lumina Desktop
lumina-fm-1.4.1                Insight file manager from the Lumina Desktop
lumina-mediaplayer-1.4.1_1     Streaming media player from the Lumina Desktop
lumina-pdf-1.4.1               PDF viewer from the Lumina Desktop
lumina-screenshot-1.4.1        Screenshot utility from the Lumina Desktop
lumina-textedit-1.4.1_1        Plaintext editor from the Lumina Desktop
~~~

packages are up to date, but I see from an updated ports tree they are built from the trueos account, not the lumia-desktop account.  Could that be the problem?

**Comment by hxw** [comment]
I just checked on the desktop and it does have the environment variable set and theme works.  Bot not on T580 which is the same set of lumina-* versions.

The only difference is that the desktop uses Nvidia; built from a port as ndidia-driver pkg crashes X (probably as kernel is 11.2-p3 and packages are built on 11.1).  The T580 uses drm-nex-kmod built from ports and uses intel driver for x.

There is another problem with Desktop/nvidia in that having the start menu in the panel immediately crashed lumina at login, I can add the option later and the menu is operational

I think I will have to try to compare the two systems to see if I can find any differences

**Comment by hxw** [comment]
I have updated another machine (T420) and the environment is now correct, so latest package is setting theme correctly.  T580 must not be correctly updated.

The latest package just has the crashes on login if `systemstart` is part of panel config.  workaround is to delete it, login then add it back after panel is established

**Comment by hxw** [comment]
I think theme env is ok on current Lumina package on  FreeBSD 11.2-RELEASE-p3:
```
# pkg info |grep lumina
lumina-1.4.1,3                 Lumina Desktop Environment (meta-port)
lumina-archiver-1.4.1          Archive manager from the Lumina Desktop
lumina-calculator-1.4.1        Scientific calculator from the Lumina Desktop
lumina-core-1.4.1              Lumina Desktop Environment
lumina-coreutils-1.4.1         Lumina Desktop Environment
lumina-fileinfo-1.4.1_1        File properties utility from the Lumina Desktop
lumina-fm-1.4.1                Insight file manager from the Lumina Desktop
lumina-mediaplayer-1.4.1_1     Streaming media player from the Lumina Desktop
lumina-pdf-1.4.1               PDF viewer from the Lumina Desktop
lumina-screenshot-1.4.1        Screenshot utility from the Lumina Desktop
lumina-textedit-1.4.1_1        Plaintext editor from the Lumina Desktop
```

**Comment by hxw** [comment]
Theme is working on all systems after ensuring all packages are correctly up-to-date.

crash was cause by malloc setting for Firefox:
`export MALLOC_CONF='narenas:1,tcache:false'`
I just commented the above line: as I documented here:  https://forums.freebsd.org/threads/lumina-problems-on-11-2-release.67723/
