### ISSUE TITLE
[FEATURE REQUEST][SCREENSHOT] Upload image

### ISSUE THREAD

**Issue by lbartoletti** [lumina-desktop/lumina#625]
A low priority feature request, add the ability to upload the screenshot on a pic services like framapic, imgur, etc.
Look at ShareX and especially https://github.com/ShareX/CustomUploaders

Thanks.

**Comment by q5sys** [comment]
on sites like imgur, you can ctrl-v your clipboard contents (if your browser supports that).  So take a screencapture, click the copy button, then paste onto an imgur tab.

this could be something as an additional utility, that we can have the screenshot photo launch at user request, but Im not keen on making a screen capture utility network aware.
