### ISSUE TITLE
Lumina desktop information window have wrong link in "Ask the community" button

### ISSUE THREAD

**Issue by samob** [lumina-desktop/lumina#629]
If I open lumina-info window and click on the "Ask the community" button, it redirects to non existing website URL https://gitter.im/trueos/lumina?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
![about-lumina](https://user-images.githubusercontent.com/335163/46598783-96230880-cae5-11e8-8efe-34ccf45f515e.png)

Tested on TrueOS 18.03 and Trident Beta 03

**Comment by beanpole135** [comment]
Fixed.
