### ISSUE TITLE
Dashboard doesn't check/remember brightness

### ISSUE THREAD

**Issue by outpaddling** [lumina-desktop/lumina#631]
Changing the screen brightness via system dashboard works great, but the next time I open the dashboard, it immediately resets brightness to 100%.

FreeBSD mako.acadix.biz 11.2-RELEASE-p4 FreeBSD 11.2-RELEASE-p4 #0: Thu Sep 27 08:16:24 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

![screenshot-2018-10-19-17-06-07](https://user-images.githubusercontent.com/11299711/47246027-50a5eb80-d3c1-11e8-9b07-467b72607b41.png)

FreeBSD mako.acadix  bacon ~ 84: pkg info lumina
lumina-1.4.1,3
Name           : lumina
Version        : 1.4.1,3
Installed on   : Fri Oct 19 12:06:52 2018 CDT
Origin         : x11/lumina
Architecture   : FreeBSD:11:*
Prefix         : /usr/local
Categories     : x11
Licenses       : BSD3CLAUSE
Maintainer     : jt@ixsystems.com
WWW            : http://lumina-desktop.org
Comment        : Lumina Desktop Environment (meta-port)
Annotations    :
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 378B
Description    :
The Lumina Desktop Environment is a lightweight system interface that is 
designed for use on any Unix-like operating system. It takes a 
plugin-based approach, allowing the entire interface to be assembled or
arranged by each individual user as desired, with a system-wide default 
layout which can be customized by the system administrator. This allows 
every system (or user session) to be designed to maximize the individual 
user's productivity.

This meta-package installs all the packages related to the Lumina desktop.
If you want more fine-grained control over the installed utilities, please
install the individual x11/lumina-* and deskutils/lumina-* packages instead. 

WWW: http://lumina-desktop.org

**Comment by beanpole135** [comment]
This is already fixed in source.
There was just an error in the routine which fetches the current brightness, and that was "resetting" the brightness back to 100.
