### ISSUE TITLE
Crash under Gentoo

### ISSUE THREAD

**Issue by Piggoz** [lumina-desktop/lumina#641]
When I try to run Lumina-desktop under Gentoo, I do have this error when I try to load the program:

[  102.581752] lumina-desktop[3200]: segfault at 100000020 ip 00007f42d78bd8ee sp 00007ffd1f69f9f0 error 4 in libQt5Widgets.so.5.11.1[7f42d76c0000+623000] 

Here my Lumina Desktop version:
x11-wm/lumina-1.3.0_p1

My OS version:
Linux gentoo 4.14.83-gentoo #1 SMP Mon Dec 10 19:37:20 CET 2018 x86_64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz GenuineIntel GNU/Linux

First thing I did try is to rebuild both Lumina and Qt5widgets, with no luck. Both build fine then when I try to load lumina-desktop, it crash late in the load when the desktop seems load fine always with this same error and this same errors codes.

I don't know what I should try.

Thank you in advance for any help.

**Comment by darthsidux** [comment]
I'm getting similar crash while trying to launch lumina-1.4.0p1_1 on voidlinux also...
$lumina-desktop 
 - Created new single-instance lock
Number of XCB screens: 1
Loading Locale: "lumina-desktop" "en_US" "utf8"
Initializing Session
Starting System Tray: 0
System Tray Started Successfully
 - Initialize system menus
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 780, resource id: 56623120, major code: 143 (Unknown), minor code: 1
Auto App List Update: QDateTime(2018-12-25 08:28:57.590 PST Qt::TimeSpec(LocalTime)) Files Found: 89
QFileSystemWatcher::removePaths: list is empty
Session Tray: Window Added
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(1871,413 49x253) "Xfce4-panel"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(0,0 1920x1080) "Xfdesktop"
 -- Found Screen: 0
 -- Is Fullscreen!
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(123,70 1577x975) "Firefox"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(1076,283 747x547) "Thunar"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(85,111 928x957) "Geany"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(535,311 807x689) "libreoffice-calc"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(891,42 974x557) "Xfce4-terminal"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(1321,42 538x449) "vlc"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(140,357 1119x674) "Hexchat"
 -- Found Screen: 0
 - Update Desktops
  Screen Count: 1
  DESKTOPS Length: 0
" -- Screen[0]:" QRect(0,0 1920x1080)
 - Start desktop on screen: 0
Found Settings Change: "DVI-0"
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
Empty filename passed to function
QMetaObject::connectSlotsByName: No matching signal for on_tool_restart_update_clicked()
Empty filename passed to function
Empty filename passed to function
Resync Size: QSize(100, 30) QSize(336, 466)
 - after menu resize: QSize(336, 466) QSize(336, 466)
Updating clock format
Verify Clock width: 1 55 ("8:28 AM")
Verify Clock width: 1 55 ("8:28 AM")
Invalid Panel Plugin: "battery---0.0.1"  -- Ignored
Check Panel Focus: 0 37 37 QSize(1920, 37)
Check Panel Focus: 1 2 32 QSize(192, 32)
Got Root Size Change
Got Root Size Change
Verify Clock width: 1 55 ("8:29 AM")
Invalid Panel Plugin: "battery---0.0.1"  -- Ignored
Check Panel Focus: 0 37 37 QSize(1920, 37)
Check Panel Focus: 1 2 32 QSize(192, 32)
Verify Clock width: 1 55 ("8:29 AM")
Launching startup applications
 - Loading previous settings
 - - Audio Volume: "50%"
 - Initialize media player
Verify Clock width: 1 55 ("8:29 AM")

** (lumina-desktop:4846): CRITICAL **: 08:29:00.411: file gstaudioringbuffer.c: line 2045 (gst_audio_ring_buffer_set_channel_positions): should not be reached
Visual Tray Started: "systemtray---0.0.1" true
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
 - Update Desktops
  Screen Count: 1
  DESKTOPS Length: 1
" -- Screen[0]:" QRect(0,0 1920x1080)
 - Show desktop on screen: 0
Update WM
 - Visual System Tray: Add Icon: 35651596
Found Settings Change: "DVI-0"
zsh: segmentation fault  lumina-desktop

Then from gdb....
gdb
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) lumina-desktop
Undefined command: "lumina-desktop".  Try "help".
(gdb) run
Starting program:  
No executable file specified.
Use the "file" or "exec-file" command.
(gdb) file lumina-desktop
Reading symbols from lumina-desktop...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/lumina-desktop 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffeed30700 (LWP 6059)]
 - Created new single-instance lock
Number of XCB screens: 1
Loading Locale: "lumina-desktop" "en_US" "utf8"
[New Thread 0x7fffee303700 (LWP 6060)]
[New Thread 0x7fffdf1ec700 (LWP 6061)]
[New Thread 0x7fffde9eb700 (LWP 6062)]
[New Thread 0x7fffde1ea700 (LWP 6063)]
[New Thread 0x7fffdd9e9700 (LWP 6064)]
[New Thread 0x7fffdd1e8700 (LWP 6065)]
[New Thread 0x7fffdc9e7700 (LWP 6066)]
[New Thread 0x7fffc7fff700 (LWP 6067)]
[New Thread 0x7fffc77fe700 (LWP 6068)]
[New Thread 0x7fffc6ffd700 (LWP 6069)]
Initializing Session
Starting System Tray: 0
System Tray Started Successfully
 - Initialize system menus
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 764, resource id: 35651600, major code: 143 (Unknown), minor code: 1
Auto App List Update: QDateTime(2018-12-25 08:33:07.208 PST Qt::TimeSpec(LocalTime)) Files Found: 89
QFileSystemWatcher::removePaths: list is empty
[New Thread 0x7fffc67fc700 (LWP 6073)]
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(1871,413 49x253) "Xfce4-panel"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(0,0 1920x1080) "Xfdesktop"
 -- Found Screen: 0
 -- Is Fullscreen!
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(123,70 1577x975) "Firefox"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(1076,283 747x547) "Thunar"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(85,111 928x957) "Geany"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(535,311 807x689) "libreoffice-calc"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(891,42 974x557) "Xfce4-terminal"
 -- Found Screen: 0
 -- Check Window Geom: QRect(0,0 1920x1080) QRect(140,357 1119x674) "Hexchat"
 -- Found Screen: 0
 - Update Desktops
  Screen Count: 1
  DESKTOPS Length: 0
" -- Screen[0]:" QRect(0,0 1920x1080)
 - Start desktop on screen: 0
Found Settings Change: "DVI-0"
[New Thread 0x7fffc5ffb700 (LWP 6074)]
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
Empty filename passed to function
QMetaObject::connectSlotsByName: No matching signal for on_tool_restart_update_clicked()
Empty filename passed to function
Empty filename passed to function
Resync Size: QSize(100, 30) QSize(336, 466)
 - after menu resize: QSize(336, 466) QSize(336, 466)
Updating clock format
Verify Clock width: 1 55 ("8:33 AM")
Verify Clock width: 1 55 ("8:33 AM")
Invalid Panel Plugin: "battery---0.0.1"  -- Ignored
Check Panel Focus: 0 37 37 QSize(1920, 37)
Check Panel Focus: 1 2 32 QSize(192, 32)
Got Root Size Change
Got Root Size Change
Verify Clock width: 1 55 ("8:33 AM")
Invalid Panel Plugin: "battery---0.0.1"  -- Ignored
Check Panel Focus: 0 37 37 QSize(1920, 37)
Check Panel Focus: 1 2 32 QSize(192, 32)
Verify Clock width: 1 55 ("8:33 AM")
Launching startup applications
 - Loading previous settings
 - - Audio Volume: "50%"
 - Initialize media player
[New Thread 0x7fffaa79a700 (LWP 6096)]
[Thread 0x7fffaa79a700 (LWP 6096) exited]
[New Thread 0x7fffaa79a700 (LWP 6097)]
[Thread 0x7fffaa79a700 (LWP 6097) exited]
[New Thread 0x7fffaa79a700 (LWP 6098)]
[Thread 0x7fffaa79a700 (LWP 6098) exited]
[New Thread 0x7fffaa79a700 (LWP 6102)]
[New Thread 0x7fffa9b65700 (LWP 6103)]
[New Thread 0x7fffa914c700 (LWP 6104)]
Verify Clock width: 1 55 ("8:33 AM")
[New Thread 0x7fff9bfff700 (LWP 6105)]
[New Thread 0x7fff9b7fe700 (LWP 6106)]
[New Thread 0x7fff9adf5700 (LWP 6107)]

** (lumina-desktop:6052): CRITICAL **: 08:33:10.313: file gstaudioringbuffer.c: line 2045 (gst_audio_ring_buffer_set_channel_positions): should not be reached
[New Thread 0x7fff9a5f4700 (LWP 6108)]
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Visual Tray Started: "systemtray---0.0.1" true
 - Update Desktops
  Screen Count: 1
  DESKTOPS Length: 1
" -- Screen[0]:" QRect(0,0 1920x1080)
 - Show desktop on screen: 0
Update WM
Found Settings Change: "DVI-0"

Thread 1 "lumina-desktop" received signal SIGSEGV, Segmentation fault.
0x00007ffff7320505 in ?? () from /usr/lib/libQt5Widgets.so.5
(gdb) backtrace
#0  0x00007ffff7320505 in ?? () from /usr/lib/libQt5Widgets.so.5
#1  0x00007ffff7320623 in ?? () from /usr/lib/libQt5Widgets.so.5
#2  0x00007ffff72ad1f7 in QWidgetPrivate::inheritStyle() ()
   from /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff72acf3c in QWidgetPrivate::setStyle_helper(QStyle*, bool, bool)
    () from /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff72ad25b in QWidgetPrivate::inheritStyle() ()
   from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff72acf3c in QWidgetPrivate::setStyle_helper(QStyle*, bool, bool)
    () from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff72ad25b in QWidgetPrivate::inheritStyle() ()
   from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff72acf3c in QWidgetPrivate::setStyle_helper(QStyle*, bool, bool)
    () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff72ad25b in QWidgetPrivate::inheritStyle() ()
   from /usr/lib/libQt5Widgets.so.5
#9  0x00005555555f8b7d in ?? ()
#10 0x00007ffff666ec92 in QObject::event(QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#11 0x00007ffff72bcc5b in QWidget::event(QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff727e491 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit--- 
#13 0x00007ffff7285ad0 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff6645199 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff664818b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#16 0x00007ffff6697823 in ?? () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff44b79de in g_main_context_dispatch ()
   from /usr/lib/libglib-2.0.so.0
#18 0x00007ffff44b7c78 in ?? () from /usr/lib/libglib-2.0.so.0
#19 0x00007ffff44b7d0c in g_main_context_iteration ()
   from /usr/lib/libglib-2.0.so.0
#20 0x00007ffff6696e53 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#21 0x00007fffefdd07f1 in ?? ()
   from /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5
#22 0x00007ffff6643e6b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#23 0x00007ffff664bfe2 in QCoreApplication::exec() ()
   from /usr/lib/libQt5Core.so.5
#24 0x0000555555587af4 in main ()
(gdb)

**Comment by grozin** [comment]
I have, probably, the same problem. I had 2 Gentoo computers and run Lumina 1.4.0 patchset 1 for a long time, with Qt-5.9.6. After upgrading Qt to 5.11.x, lumina does not start. I had to downgrade Qt to 5.9.6, because lumina is my main desktop, and I cannot use my computers without it. Now I bought a new laptop, and installed Gentoo on it. I installed Qt-5.11.3 (5.9.6 is no longer in the repository). I start X by startx; my .xinitrc is basically exec start-lumina-desktop. What I get is

grozin@bilbo ~ $ startx
...
X.Org X server 1.20.3
...
Starting the Lumina desktop on current X11 session: ":0"
 - Resetting the monitor configuration to the last-used settings
 - Starting the session...
[Lumina] Checking User Files
 - Old version: "1.4.0"
 - Current version: "1.4.0"
 - Make changes: false
Finished with user files checks
Got Desktop Process Finished: 11
Finished Closing Down Lumina
xinit: connection to X server lost

After startx, the usual lumina splash screen appears; then the usual lumina main screen appears for a split second, and then I return to the text mode. By the way, I use an intel video card.

Is lumina 1.4.0 patchset 1 incompatible with recent versions of Qt? Should I try the current git snapshot of lumina?

**Comment by Piggoz** [comment]
Hello, I can see you grozin are the maintainer of Gentoo ebuilds. Both 1.13 and 1.14 builds as I said in my original post, build completely fine then when you try to load it, it crash related with qtwidgets like I explained in my original post.

This problem in my tests seems limited to x86_64 platform. Pure x86 seems to work ok.

Like this, the ebuild for Gentoo x86_64 platform seems useless. I hope you can fix it.

Thank you in advance.

**Comment by Piggoz** [comment]
My idea, now, after all this time from when the issue started, is Lumina Desktop is not mainteined anymore by developers, this nice light desktop is a BSD native app for TrueOS and considering also TrueOS seems pretty much dead (judging from they're site, probably we can never have a fix for Lumina Desktop, especially under Linux. R.I.P. Lumina Desktop, this the problem often with free software.

**Comment by beanpole135** [comment]
@Piggoz : Not quite.
Lumina Desktop developers only actively maintain crash fixes for FreeBSD and derivative OS's. For Linux OS support we will gladly accept patches/fixes from people running that distro/OS, but we do not actively install/test Lumina on non-BSD operating systems.

**Comment by beanpole135** [comment]
The ebuild scripts in the Lumina repository were only committed at the behest of the Gentoo port maintainer, to make it easier for everyone to see/use the same scripts.
If those scripts are out of date and no longer work, I will gladly remove them from the repo or tag them as obsolete as necessary.

**Comment by beanpole135** [comment]
I just want to point out that FreeBSD has Qt 5.12.x right now, and was using Qt 5.11.x earlier without any troubles from Lumina/Qt at all.
As a quick scan of the gdb backtrace shows, it appears that the Qt libraries you are using on Gentoo/Void linux are not built properly and/or not compatible with something in your OS. In particular, it appears to be something in the graphics support integrations for Qt:
```
#0 0x00007ffff7320505 in ?? () from /usr/lib/libQt5Widgets.so.5
#1 0x00007ffff7320623 in ?? () from /usr/lib/libQt5Widgets.so.5
#2 0x00007ffff72ad1f7 in QWidgetPrivate::inheritStyle() ()
from /usr/lib/libQt5Widgets.so.5
#3 0x00007ffff72acf3c in QWidgetPrivate::setStyle_helper(QStyle*, bool, bool)
() from /usr/lib/libQt5Widgets.so.5
#4 0x00007ffff72ad25b in QWidgetPrivate::inheritStyle() ()
from /usr/lib/libQt5Widgets.so.5
#5 0x00007ffff72acf3c in QWidgetPrivate::setStyle_helper(QStyle*, bool, bool)
() from /usr/lib/libQt5Widgets.so.5
```

**Comment by Piggoz** [comment]
Qt-5.11.3 used on my two Gentoo 64 bit systems failing on qt5widgets in lumina-desktop, can run latest Plasma desktop and his widgets without any problem, they can also run single Qt apps (like qterminal, qzilla, etc) under other desktops without any problem, so I will doubt there is a configuration problem on the way Qt was configured. Needless to say, Lumina-desktop do run perfectly fine under qt-5.9.x library. Again: the problem is not present in pure x86 machine. Just x86_64. And BTW, th video driver installed doen’t change anything: it crash even with the vesa or fb video driver, tested personally by me.

Again, the Lumina Gentoo maintainer, grozin, has posted on this thread that 999 release seems to load fine then it is unresponsive. I didn’t try.

I read about a possible future Lumina desktop version 2, rumored now for long times, then reading developers comments here, seems the project is not under development anymore. Just fix for the BSD world.

For me was an interesting project, too bad people lack interest for it.

**Comment by beanpole135** [comment]
Lumina 2.0 is still in development, but I got tired of people harassing me about things that don't work yet when manually building/testing an *unreleased, in-development* version of the project in spite of being asked not to yet. 
Because of this I have started hiding that code/work and I will be pushing it to GitHub later when I am ready for people to start trying it out.
