### ISSUE TITLE
[FEATURE REQUEST] Retain app window focus

### ISSUE THREAD

**Issue by GHNewbiee** [lumina-desktop/lumina#648]
Prevent, through an option, applications being in the opening state/phase from stealing the window focus from the running/current one.

A newly launched app starts "behind" or "under" the current window. Even if, an input is required, for example a password, this should still open "behind" or "under" the current window. Such a required "activity" should only be displayed in the panel (for example, by flashing).

Stealing focus is very annoying!

Tia

**Comment by beanpole135** [comment]
Focus options are already available in the Fluxbox configuration settings:
lumina-config -> Appearance -> Window Manager -> Focus Policy
I think the one you want is "Strict Mouse Focus" (ensure the window directly under the mouse always has focus).

**Comment by GHNewbiee** [comment]
So, if I choose 4 new apps to open, for example firefox with password request, chrome, libreoffice and visual studio code but still keep on working with text editor, none of them will steal the focus in the near future!? No password modal will appear on my screen interrupting my work even if the mouse is left on menu bar?
