### ISSUE TITLE
website certification invalid (https://www.lumina-desktop.org/)

### ISSUE THREAD

**Issue by jrmarino** [lumina-desktop/lumina#655]
on both MSIE and chrome, I'm seeing an error similar to:
```
This site is not secure

This might mean that someone’s trying to fool you or steal any info you send to the server. You should close this site immediately.

Go to your Start page
Details 
The hostname in the website’s security certificate differs from the website you are trying to visit.
Error Code: DLG_FLAGS_SEC_CERT_CN_INVALID
Go on to the webpage (Not recommended)
```

It looks like the site needs a new certificate

**Comment by beanpole135** [comment]
There is a new website up and running for Lumina, but there still appears to be an old cert attached to the DNS chain right now (the iXsystems IT dept has already been informed and is working on a fix).

In the meantime, just go to "http://lumina-desktop.org" and it will properly redirct you to the new website (with a new SSL cert).

**Comment by jrmarino** [comment]
It might have been better to leave this issue open until the problem is actually resolved.
As of today, it hasn't been.  Maybe IT dept needs a reminder.

**Comment by beanpole135** [comment]
Thanks for the reminder, I worked with the IT guy this afternoon and we got this nailed down and fixed now.
Seems to be working properly for all versions of the lumina-desktop.org URL address now (http, https, with www.*, without www.*)
