### ISSUE TITLE
Lumina-Config -- panel page -- swap panels between screens

### ISSUE THREAD

**Issue by q5sys** [lumina-desktop/lumina#658]
We really should have a simple way to transfer a panel from one screen to another.  Not sure of the best way to implement this, but it's something we should do eventually.

**Comment by beanpole135** [comment]
In the lower-left corner of the panel configuration page, there is already a "profile" button which will allow you to copy panel settings from one monitor (whether it is currently-active or not) to the currently-selected monitor.
