### ISSUE TITLE
lumina-pdf crashes on search function

### ISSUE THREAD

**Issue by RodMyers** [lumina-desktop/lumina#664]
when opening a large PDF, 100 page, from the shell, it immediately crashes, with this in the terminal;

lumina-pdf Desktop/ham/TMV7A.pdf
Loading Locale: "l-pdf" "en_US" "UTF-8"
[1]    63378 segmentation fault  lumina-pdf TMV7A.pdf

 - Document Setup : start loading pages now
[1]    63378 segmentation fault  lumina-pdf Desktop/ham/TMV7A.pdf
[TMV7A.pdf](https://github.com/lumina-desktop/lumina/files/2831972/TMV7A.pdf)

**Comment by beanpole135** [comment]
This appears to be fixed now in the latest version from source now.
