### ISSUE TITLE
lumina-fm doesnt update active browser widget

### ISSUE THREAD

**Issue by q5sys** [lumina-desktop/lumina#665]
1) Have file manager open to some directory.
2) Select a file and rename it.
Result:  File disappears from view.  F5 does not refresh and load it.
You have to back out of the directory and re-enter it for the file to show.

This ticket is less 'fix this now' and more a tracking ticket.
Once I can get back to replacing the backend with qfilesystemmodel this will probably be resolved.

**Comment by beanpole135** [comment]
This is fixed in Project Trident 18.12-U8 (Lumina sources within the last two weeks)

**Comment by utrenkner** [comment]
Just upgraded to 1.5.0 and can confirm: This bug is gone! Many thanks.
