### ISSUE TITLE
no release posted within 2018, is this project still active?

### ISSUE THREAD

**Issue by addriumruss** [lumina-desktop/lumina#666]
no release posted within 2018, is this project still active?

**Comment by q5sys** [comment]
Yes, the project is still active.   We had to stop and focus on Project Trident for most of 2018, which is why there is a drop in development.  But dont worry, the project is still very much alive.

**Comment by maxsteciuk** [comment]
Project Trident actively ships it, constantly under testing and usage 

Also commit history can be one indicator
