### ISSUE TITLE
Lumina Window Manager Default Theme No Draggable Windows

### ISSUE THREAD

**Issue by possnfiffer** [lumina-desktop/lumina#669]
By default, when you install Lumina on vanilla FreeBSD you get no borders on the windows. I wrote the following to Ken April 2018

> Hi Ken,
> 
> We met at BSD Can this last year. I believe we chatted about the bug report I sent you when installing Lumina on a 32 bit machine the Fluxbox config was messed up for some reason. Anyway, I feel like that issue has cropped up again or something similar due to the way that Lumina looks when I install in on vanilla FreeBSD. So the FreeBSD Foundation is doing this FreeBSD Installfest on Monday and I've volunteered to help out. I've convinced everyone we're using Lumina for the desktop environment for obvious resons ;p and I've been working on the steps needed to get everything working properly. I'll include the steps I'm using and the walkthrough video I made with ffmpeg. If you could let me know if Lumina looks right or not that would be great.
> 
> Best Regards,
> Roller
> 
> https://drive.google.com/file/d/1yCrHqEPiLEscTvOHN5yUnSyJdNDUHJ24/view

Anyways so I've figured out how to fix the issue. I'm teaching the Getting Started with FreeBSD workshop at SCaLE 17x and instead of tell people about this issue, as soon as we get Lumina installed I walk people through the following configuration steps so they can have a working setup. It seems just applying a "Window Theme" from the "Window Manager" forces the drag-gable window decorations to appear and work properly.

Desktop Configuration
Right click on the desktop > Preferences > All Desktop Settings
Under Appearance click on “Theme,” then select “Icons” from the sidebar, then select “Material Design (light),” and click on “Apply.” Close the “Theme Settings” window.
Go back to the “Desktop Settings” window and select “Window Manager.” In the “Window Theme” drop-down menu, select “Twice.” Click on “Save.” Close the “Window Manager Settings” window.
Go back to the “Desktop Settings” window and select “Applications.” Set the “E-mail Client” to Firefox and “Virtual Terminal” to Sakura. Close all the settings windows.
Right click on the desktop and select “Preferences” then “Wallpaper,” click on the “+,” and choose “solid color.” We chose red for our color. Click “ok,” then “Save.”

**Comment by beanpole135** [comment]
Please double check the version of Lumina that you have installed, as well as whether you have the "fluxbox-tenr-styles-pack" installed (fluxbox themes package).

If you are trying to do this in bulk for people, you also might be interested in providing an alternative set of 
default settings by editing or installing an alternative system-wide settings file: /usr/local/etc/luminaDesktop.conf

This does not appear to be an issue on any other systems that I have tested (FreeBSD, TrueOS, or Project Trident).
