### ISSUE TITLE
Disabling Synaptics touchpad renders UI ineffective

### ISSUE THREAD

**Issue by daniel-vu** [lumina-desktop/lumina#672]
Adding the following line to /etc/sysctl.conf renders the UI shell
ineffective:

```
hw.psm.synaptics.touchpad_off=1
```

One can still interact with the shell i.e. click icons on the desktop
or the Applications menu, and animations will fire as expected, but no
processes, menus etc. ever get started.

Keyboard shortcuts still worked, so I was able to open a terminal and clear the line in `/etc/sysctl.conf` to revert the change on the next reboot. Before rebooting, I captured the dmesg in case if it is helpful.

[dmesg.boot](https://github.com/lumina-desktop/lumina/files/2954627/dmesg.txt)

**Comment by beanpole135** [comment]
This is completely unrelated to Lumina, but rather your OS relationship/configuration with running X11.
