### ISSUE TITLE
Change window manager

### ISSUE THREAD

**Issue by Mazaduk** [lumina-desktop/lumina#676]
I tried running the command `killall fluxbox && marco --replace` but it didn't work; fluxbox just showed up again.

**Comment by beanpole135** [comment]
Did you try changing your WM in the Lumina WM settings?
Lumina has some automatic monitoring in place to ensure that the listed window manager never gets killed/stopped by an external process (which is essential since for some functionality you need to restart fluxbox mid-session).

**Comment by Mazaduk** [comment]
@beanpole135 Which line do I change in the Lumina WM settings? In the simple editor there's only stuff for fluxbox, and the "advanced editor" seem to also be for the same thing. I can't find the line in the advanced editor that prevents fluxbox from quitting.
