### ISSUE TITLE
utox doesn't load in Lumina.

### ISSUE THREAD

**Issue by FrostKnight** [lumina-desktop/lumina#677]
I have tried loading utox within Lumina-desktop but it not only does not load on the dashboard, it doesn't load at all.

 I had to use xfce4-panel to load it via terminal, and the moment i closed terminal, utox disappears. 

Ps, I am using an arch derivative called Hyperbola. I compiled your latest stable version from source. 

Other than that, your desktop is awesome because it is extremely lightweight... its probably the best  in that regard even better than lxde.

**Comment by beanpole135** [comment]
That sounds like an issue with how utox expects to be launched or communicate with X11 rather than a problem with Lumina.
Without any specific details of the application error(s) I think you will need to talk to the uTox developers to see if they can help figure out why their app is not working.
