### ISSUE TITLE
readme suggests #lumina-desktop@freenode but the channel is invite only

### ISSUE THREAD

**Issue by renic** [lumina-desktop/lumina#678]
The readme is directing me to #lumina-desktop on freenode, but I can't get it because it's invite only :(

**Comment by q5sys** [comment]
Thanks for the message.  We closed down the IRC channel for now.  We're using telegram only.  We forgot to remove that from the readme, but its been done now.  
https://github.com/lumina-desktop/lumina/commit/6903713165fea9444fccecd91b1084a734f2eb0a
