### ISSUE TITLE
[Documentation] Please add a short subsection how to start lumina after it was compiled/installed successfuly, into the main README or some other document (and then a link from the README, either way works)

### ISSUE THREAD

**Issue by rubyFeedback** [lumina-desktop/lumina#681]
Hello lumina devs,

I am running linux (slackware base, but I compiled most everything from source anew) and
I just compiled lumina successfully from source, latest release from a few hours ago or so - no errors that I could see, both "make" and "make install" worked after the qmake step.

But now I am not sure how to start lumina. Oldschool Linux has classical init runlevel 3 and makes use of .xinitrc (perhaps the BSDs do too when xorg-server is started).

Typically I would use something such as "exec mate-session" to start the mate-desktop
and that works fine (I am writing this from a self-compiled mate desktop right now, for example).

I am not sure how to do this with lumina ... perhaps "exec lumina" but I am not sure. (I suppose I will find out when I look under bin/ subdirectory but it would be better, IMO, if the documentation could mention this with a sentence or two perhaps, the main README). Thanks for reading and thank you for the work with lumina - I hope it becomes a contender for on-linux usage too (although I have tried out the various BSDs, including PC-BSD or the new name, I am much more comfortable with linux; even slice-installation on the *bsds I actually found more confusing than grub/cfdisk... but this may be due to more tutorials being available on linux perhaps, not sure).

**Comment by beanpole135** [comment]
Try using "exec start-lumina-desktop".

You can find the documentation on how to start the desktop already written out in the "core" components directory.
https://github.com/lumina-desktop/lumina/blob/master/src-qt5/core/README.md

**Comment by rodlie** [comment]
@rubyFeedback : https://github.com/SlackBuildsOrg/slackbuilds/blob/master/desktop/lumina/xinitrc.lumina xinitrc for Slackware.
