### ISSUE TITLE
lumina-fm copy in parallel

### ISSUE THREAD

**Issue by madewo** [lumina-desktop/lumina#687]
If two or more copy-processes got started in parallel, the result of copy gets visible to other apps (thunar, shotwell, terminal, ... whatever) only after all copies are finished. Even if that takes hours.
To reproduce:
a) start a copy of a folder containing lots of large files
b) start a copy of a folder that contains very little volume
c) after the b) copy has finished and the a) copy still running look at the a) destination folder using any program other than lumina-fm [folder is not visible]
d) look again at the a) destination folder after the a) copy has terminated [now it's visible]

**Comment by beanpole135** [comment]
This is typically an essential design implementation during file transfers to ensure that users do not "get into" a directory/file while it is in the middle of changing and interrupt the process.

In this case, lumina-fm is just using the standard file copy/move functionality from the Qt libraries and I believe that those functions create a hidden version of the file/directory (name starting with ".") while the transfer is processing, and then rename it to the final non-hidden name when it finishes.
