### ISSUE TITLE
Install issue: Insight-FileManager.png and Lumina-DE.png install as scalable icons.

### ISSUE THREAD

**Issue by darkshram** [lumina-desktop/lumina#688]
Lumina Desktop 1.5.0 installs Insight-FileManager.png and Lumina-DE.png as scalable icons into /usr/share/icons/hicolor/scallable/apps, but they really are 64x64 PNG files. They should install into /usr/share/icons/hicolor/64x64/apps.

**Comment by q5sys** [comment]
I think the correct way to resolve this is to actually turn these into scalable SVGs like they should have been from the start.  I've put it on my todo list.

**Comment by q5sys** [comment]
wispy (lumina-de.png) has been turned into an SVG, and will be included in the next update.  https://github.com/lumina-desktop/lumina/commit/77ce50cdbed82dafb632b912cc43a4d4f648a791
A replacement SVG for Insight will be in that update as well.

**Comment by q5sys** [comment]
https://github.com/lumina-desktop/lumina/commit/a3a206d79e2a5365f29af460e0db7709f76d0e40
