### ISSUE TITLE
Update of FreeBSD port to 1.5.0 ?

### ISSUE THREAD

**Issue by utrenkner** [lumina-desktop/lumina#693]
Just a question: Do you plan to update the FreeBSD port anytime soon? I am asking because the window closes on getting 1.5.0 in the quarterly repo for the 3rd quarter 2019... would be great to have it as a official package.

Thanks for all your work!

**Comment by beanpole135** [comment]
I am not a FreeBSD port committer, nor am I the maintainer of the Lumina ports on FreeBSD.
I have created FreeBSD ports for the Lumina tools in the repo here[1], but somebody else will need to submit them to the FreeBSD repo.

```
cd [repository dir]
./mkport.sh [/path/to/ports/tree]
```
The port templates that are used to create the ports are located in "port-files" (or "pkg" - depending which repo you are looking at), if you want to see the actual templates.
Note that lumina-pdf and lumina-calculator are in their own repositories now. I am gradually moving all the  desktop utilities into their own repos to make it easier to add custom maintainers for each of them.
