### ISSUE TITLE
java.syntax for lumina text editor

### ISSUE THREAD

**Issue by mremski** [lumina-desktop/lumina#694]
[java.syntax.txt](https://github.com/lumina-desktop/lumina/files/3329632/java.syntax.txt)
I hope this attached correctly.
quick rules file for java syntax highlighting for lumina text editor.
Had to add a ".txt" extension to keep git happy.

**Comment by beanpole135** [comment]
Added! Thanks for sending that in!
https://github.com/lumina-desktop/lumina/commit/f02fe1665ed14611d00426a7a71db445d49826fb
