### ISSUE TITLE
[Feature] Support Knoppix

### ISSUE THREAD

**Issue by gjhklfdsa1** [lumina-desktop/lumina#697]
**Feature**: [Knoppix](https://www.wikipedia.org/wiki/Knoppix) Package
**Idea Solution**: Ideally, official Lumina support would make it easier for it to get listed in "KNOPPIX X-RESTART" (Knoppix's DE Selector). But, I would also like to see a [remastering](http://knoppix.net/wiki/Knoppix_Remastering_Howto) for Lumina users. 

**How?**: Knoppix is basically Debian made to be run on a Live USB/CD.
Although, not all Debian apps work out-of-the-box, many do.

_________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/78407760-feature-support-knoppix)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/BountySource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=78407760)](https://www.bountysource.com/issues/78407760-feature-support-knoppix)

**Comment by q5sys** [comment]
You would need to reach out to the Knoppix team for this.  The Lumina team does not manage packages for the individual Distros.  We are happy to accept patches from Distros to help packaging be easier (as long as it doesnt cause other conflicts), but we do not package Lumina ourselves.
