### ISSUE TITLE
Fedora build error #1

### ISSUE THREAD

**Issue by tieugene** [lumina-desktop/lumina#700]
make:
...
make[4]: Entering directory '.../lumina-1.5.0/src-qt5/core/lumina-theme-engine/src/lthemeengine-qtplugin'
make[4]: *** No rule to make target '/usr/lib/libQt5ThemeSupport.a', needed by 'liblthemeengine.so'.  Stop."

What is it? What the thing "libQt5ThemeSupport.a"?

**Comment by beanpole135** [comment]
Did you read the build notes about the core desktop package requiring the platform theme and developer packages for Qt5 in order to build the theme plugin?

https://github.com/lumina-desktop/lumina/blob/master/src-qt5/core/README.md

**Comment by tieugene** [comment]
It wants libQt5ThemeSupport.a (static (!) library).
What I can to do?

**Comment by beanpole135** [comment]
The libQt5ThemeSupport.a library is an essential part of the Qt5 "gui" module/package. See if you are missing any runtime or developer packages revolving around the Qt5 "gui" module.

**Comment by tieugene** [comment]
I found it in qt5-qtbase-static rpm (this is extra package against qt5-qtbase-devel that is for linking with dynamic qt5-qtbase).
If this is what you was planning - please note this thing in README.md (and I'll close ticket).

**Comment by beanpole135** [comment]
Done! Additional package noted in the README.
https://github.com/lumina-desktop/lumina/commit/9e7bb358b2d968f681b7c7b37ba507e61634fd00

**Comment by tieugene** [comment]
Ok, thank you.

As lumina-desktop package maintainer in Fedora I will have many questions in future.
Thank you for good feedback!
