### ISSUE TITLE
Fedora build error #2

### ISSUE THREAD

**Issue by tieugene** [lumina-desktop/lumina#701]
"lthemeengineplatformtheme.cpp:29:10: fatal error: private/qdbusmenubar_p.h: No such file or directory
   29 | #include <private/qdbusmenubar_p.h>"

**Comment by beanpole135** [comment]
Did you read the build notes about the core desktop package requiring the platform theme and developer packages for Qt5 in order to build the theme plugin?

https://github.com/lumina-desktop/lumina/blob/master/src-qt5/core/README.md

**Comment by tieugene** [comment]
Oops, private forgot.
Please add "Fedora/CentOS: qt5-qtbase-private-devel wanted" to README.md.
It was hard to find it (as for me).
Ticket can be closed.

**Comment by beanpole135** [comment]
Note about Fedora/CentOS private Qt5 devel package added to readme: https://github.com/lumina-desktop/lumina/commit/37e098e0284faff8ff31279ca66d1ed3f3400008

**Comment by tieugene** [comment]
Ok, thanks
