### ISSUE TITLE
[Doc] How to install on OpenBSD/LibertyBSD?

### ISSUE THREAD

**Issue by ghbjklhv1** [lumina-desktop/lumina#703]
**Description**: How to install on OpenBSD and LibertyBSD?

I've been trying to find install steps but neither website seems to offer any for Lumina.

**Comment by beanpole135** [comment]
If you are looking for a pre-compiled package, the OpenBSD ports collection has a slightly older version of Lumina listed right now (1.4.0.p1) : http://openports.se/search.php?so=lumina

If you are looking to compile it yourself, you just need to follow the build instructions listed here on the README for compiling from sources: https://github.com/lumina-desktop/lumina#how-to-build-from-source-
