### ISSUE TITLE
System Tray does not register autostart application

### ISSUE THREAD

**Issue by leetnc** [lumina-desktop/lumina#704]
Adding "osmo" to the autostart list does not get the osmo icon to the system tray.   Same behavior for Thunar.
Incidentally, running "osmo" from the start menu does put the osmo icon in the system tray.
Anticipated behavior was for adding system tray enabled application to result in icon going to system tray.
System: Lumina 1.5,  Dell 980, Slackware 14.2
-Norm

**Comment by beanpole135** [comment]
Did you logout and then log back in after registering the osmo application to auto-start?
The auto-start list is **only** used to launch applications at the end of the login process. It does not start the application at the time that you register it.

**Comment by leetnc** [comment]
Affirmative.
Made the configuration change to add osmo to the autostart list, verified a
checkmark in the block to the left,  did the Save, logged out, re-started
Lumina.  Osmo comes up as an active window and is also on the lower panel
at the left side.   There is no icon in the system tray.
Curiously,  "Network" comes up in the system tray just fine if checked in
the autostart list.    And "Orage Calendar" comes up just fine in the
system tray if I add it to the autostart list.
Osmo does come up in the system  tray if I run it from the start menu.   It
does not come up in the system tray if initiated via  the autostart list.
-Norm

**Comment by beanpole135** [comment]
How did you register the auto-start? Did you use the application link or the binary/file link?
I am wondering if the *.desktop link for osmo (which the start menu uses) has a different startup routine to initialize the system tray than just running the "osmo" binary.

If you use the application link, then I am kind of at a loss as to what is different: the autostart is running the exact same startup routine for the app in that case that the start menu uses - and autostart already waits to start apps until after the desktop (and system tray) are already up and running, so there should not be any timing issues with that unless there is some other system service which osmo can't connect to until later.

**Comment by leetnc** [comment]
I used the application link for the auto-start.
In the meantime, I experimented with a leftover virtualbox setup that had
Lumina  1.3 installed.  It worked fine, with auto-start populating the
system tray as expected.  The slackware philosophy is that of the
integrated blob.  You install all the packages, and everything is supposed
to work.  I generally leave out KDE to save some disk space (old habit).
The virtualbox had KDE packages installed.  There is a lot of qt stuff
embedded in KDE.  Possibly there could be a Slackware KDE QT dependency
with the System Tray.
Will do some better controlled experiments to see if I can isolate the
behavior to KDE.
You make a pretty convincing argument that the problem is not on the Lumina
side.

**Comment by leetnc** [comment]
The KDE gambit was blind alley.
I did a fresh slackware 14.2 (with KDE)  install to a virtualbox, and the
system tray behavior did not change at all.
Lumina 1.3.0-p1 just seems to accommodate whatever the osmo 0.4.2
peculiarities are regards the system tray.
In Lumina 1.5.0, some applications work fine, some do not show up in the
system tray.
I may poke further into the system tray workings of osmo, but it isn't
going to be a priority.
C'est La Vie !

**Comment by leetnc** [comment]
OSMO works fine in the system tray with Void-Linux  /  Lumina 1.6.0.
Lumina 1.6.0 does not compile for Slackware 14.2, perhaps due to aging libraries in the distribution.
