### ISSUE TITLE
Can you make pulseaudio dependencies optional?

### ISSUE THREAD

**Issue by FrostKnight** [lumina-desktop/lumina#708]
For linux or other desktops?

My distro will soon have two options, alsasound or sndio.  

So yeah... libpulse keeps getting in the way of me installing this.

**Comment by beanpole135** [comment]
Lumina does not have any pulseaudio dependencies.
Lumina just uses the Qt5-Multimedia framework/module for interacting with the sound system. You probably just need to change a package/build flag for that module to switch between other sounds systems on your distro of choice. On FreeBSD, qt5-multimedia is using the ALSA backend by default, and Pulse support is an optional build flag.

**Comment by FrostKnight** [comment]
> Lumina does not have any pulseaudio dependencies.
> Lumina just uses the Qt5-Multimedia framework/module for interacting with the sound system. You probably just need to change a package/build flag for that module to switch between other sounds systems on your distro of choice. On FreeBSD, qt5-multimedia is using the ALSA backend by default, and Pulse support is an optional build flag.

Hmm... are you sure it doesn't have a libpulse dependency?  If it isn't, how would I do this?

**Comment by beanpole135** [comment]
The only thing that even remotely uses pulse in Lumina is the custom shortcuts for opening the audio mixer that are baked into the OS-specific functionality class: 
For example: https://github.com/lumina-desktop/lumina/blob/master/src-qt5/core/libLumina/LuminaOS-Linux.cpp

Even that just says to look for a tool called "pavucontrol" before providing a shortcut. It does not link to the pulse libraries or anything and is just a shortcut for launching an external utility.

**Comment by FrostKnight** [comment]
okay, but what about this error:  

/usr/bin/ld: cannot find -lpulse-mainloop-glib
/usr/bin/ld: cannot find -lpulse
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:569: lumina-desktop] Error 1

I get this when I go to do the make command.  :/

Any thoughts as to why that happens?

**Comment by FrostKnight** [comment]
Or for that matter, how I can bypass it?

**Comment by q5sys** [comment]
What Distro are you building Lumina on?

**Comment by q5sys** [comment]
Also, can you provide the compile output of a few dozen lines before you
get this error?
And just for completeness, please output the result of `uname -a` and
`qmake -v`
That'll help us try to figure out what's going on.

**Comment by FrostKnight** [comment]
Hyperbola is my first answer, as for what you told me to do, I will do it now since you ask.

**Comment by FrostKnight** [comment]
right then, first thing: 
QMake version 3.1
Using Qt version 5.8.0 in /usr/lib

second thing:

Linux user$ 4.9.194-gnu-1-lts #1 SMP Thu Sep 26 03:47:36 UTC 2019 x86_64 GNU/Linux

hmm, do you think my qmake is too old or the, linux kernel being too old might have an effect?

**Comment by FrostKnight** [comment]
I have almost zero idea why and it makes absolutely no sense, but the problem appears solved.  I can build it again for some unknown reason. Must've been some random error... Well... solved.
