### ISSUE TITLE
Desktop settings window size

### ISSUE THREAD

**Issue by outpaddling** [lumina-desktop/lumina#709]
I'd like to suggest a simple change to the default desktop settings window size, to silence the scroll bar.  It seems to me that the available settings categories easily fit a relatively small window:

[http://acadix.biz/settings-good-size.png](http://acadix.biz/settings-good-size.png)

Thanks,

    JB

**Comment by q5sys** [comment]
I'm in the middle of reworking lumina-config, but I've still got a ways to go.  I'll work on setting a larger size for the window as default.

**Comment by q5sys** [comment]
Fixed with https://github.com/lumina-desktop/lumina/pull/780
