### ISSUE TITLE
Error when trying to install on Debian 9.6

### ISSUE THREAD

**Issue by CHAOS-en-Krojerk** [lumina-desktop/lumina#710]
When I'm trying to compile using make/make install, it gives me the following compilation errors:

../libLumina/LuminaX11.cpp: In member function ‘QIcon LXCB::WindowIcon(WId)’:
../libLumina/LuminaX11.cpp:501:6: error: ‘qsizetype’ was not declared in this scope
  for(qsizetype i=0; i<image.sizeInBytes()/4; ++i, ++dat){
      ^~~~~~~~~
../libLumina/LuminaX11.cpp:501:21: error: ‘i’ was not declared in this scope
  for(qsizetype i=0; i<image.sizeInBytes()/4; ++i, ++dat){
                     ^
../libLumina/LuminaX11.cpp:501:29: error: ‘class QImage’ has no member named ‘sizeInBytes’
  for(qsizetype i=0; i<image.sizeInBytes()/4; ++i, ++dat){
                             ^~~~~~~~~~~
../libLumina/LuminaX11.cpp: In member function ‘void LXCB::paintRoot(QRect, const QPixmap*)’:
../libLumina/LuminaX11.cpp:550:12: error: ‘class QImage’ has no member named ‘sizeInBytes’
  0, qimage.sizeInBytes(), qimage.bits());
            ^~~~~~~~~~~
Makefile:1283: recipe for target '.build/obj/LuminaX11.o' failed
make[3]: *** [.build/obj/LuminaX11.o] Error 1
make[3]: Leaving directory '/root/lumina/src-qt5/core/lumina-desktop'
Makefile:47: recipe for target 'sub-lumina-desktop-make_first' failed
make[2]: *** [sub-lumina-desktop-make_first] Error 2
make[2]: Leaving directory '/root/lumina/src-qt5/core'
Makefile:44: recipe for target 'sub-core-make_first' failed
make[1]: *** [sub-core-make_first] Error 2
make[1]: Leaving directory '/root/lumina/src-qt5'
Makefile:42: recipe for target 'sub-src-qt5-make_first' failed
make: *** [sub-src-qt5-make_first] Error 2

What I did before:
* su -
* apt-get install build-essential git qt5-default qttools5-dev-tools libqt5gui5 qtmultimedia5-dev libqt5multimediawidgets5 libqt5network5 libqt5svg5-dev libqt5x11extras5-dev libxcb-icccm4-dev libxcb-ewmh-dev libxcb-composite0-dev libxcb-damage0-dev libxcb-util0-dev libphonon-dev libxcomposite-dev libxdamage-dev libxrender-dev libxcb-image0-dev libxcb-screensaver0-dev qtdeclarative5-dev fluxbox kde-style-oxygen xscreensaver xbacklight alsa-utils acpi numlockx pavucontrol xterm sysstat git
* git clone https://github.com/trueos/lumina.git
* cd lumina
* qmake LINUX_DISTRO=Debian
* make (fails here)

**Comment by lbartoletti** [comment]
Can you try by including #include <QtGlobal> in `LuminaX11.cpp`?
What is your version of Qt?

**Comment by CHAOS-en-Krojerk** [comment]
Qt version 5.7.1. Tried to add #include <QtGlobal> in LuminaX11.cpp, I still get the same errors.

**Comment by lbartoletti** [comment]
Qt version is too old. https://doc.qt.io/qt-5/qimage.html#sizeInBytes 

After https://github.com/lumina-desktop/lumina/pull/706 minimal Qt version should be 5.11... 

cc @beanpole135

**Comment by beanpole135** [comment]
After some review, it appears that the QImage size function change is fairly important to Qt, as there are some significant warnings about file sizes and such on the depricated function, so I am leaning toward just documenting the new minimum Qt version for the master branch of the Lumina desktop sources.
By the same token, it appears that the new size functions were added in Qt 5.10, unless @lbartoletti is aware of some other functions aside from the QImage::sizeInBytes() that were added which Qt 5.11

**Comment by q5sys** [comment]
Im closing this as it seems that a newer qt version was the solution, and the documentation has been udpated.
