### ISSUE TITLE
Should Lumina-DE.desktop use absolute pathnames?

### ISSUE THREAD

**Issue by outpaddling** [lumina-desktop/lumina#713]
Currently it contains:

Exec=start-lumina-desktop
TryExec=start-lumina-desktop

I found that this does not work with SLiM login manager.

Should these be expanded to absolute pathnames?  This could be considered a SLiM or local env issue as well, but it seems to me an absolute pathname would be safer than relying on PATH in this case.

**Comment by q5sys** [comment]
Im not 100% sure, but I think the reason this was not made absolute is that some OS's put things in different places.  ie. /usr/bin vs /bin
Hard coding the path will break it for any OS using a different path

**Comment by outpaddling** [comment]
I failed to mention that this is on FreeBSD.  We could leave it alone in the source and patch it in the FreeBSD port, or just blame it on SLiM.  There may be other desktop envs that don't use absolute pathnames either.
