### ISSUE TITLE
Can I run a lumina host as a remote desktop server(rdp)？

### ISSUE THREAD

**Issue by itstmyi** [lumina-desktop/lumina#716]
I use FreeBSD as the server's OS and would like to use a  rdp client from MS Windows . 

Thanks .

**Comment by q5sys** [comment]
RDP specifically or vnc?  I've used VNC before with no issues.

**Comment by q5sys** [comment]
Using VNC on windows to connect to Linux running the Lumina Desktop:

![image](https://user-images.githubusercontent.com/4654247/78850793-1467b000-79e6-11ea-9411-56bf159226be.png)
