### ISSUE TITLE
Ubuntu 19.10 - compile errors

### ISSUE THREAD

**Issue by KaiLyons** [lumina-desktop/lumina#722]
![VirtualBox_Ubuntu Lumina_11_03_2020_21_52_22](https://user-images.githubusercontent.com/50976878/76485610-9f9f5700-63e2-11ea-8b24-5ee25c51734d.png)
What I can tell it is that it is an issue with a Qt Theming Engine. I looked through errors for the past hour trying to filter what I need to see and found nothing that I know works.

OS: Ubuntu 19.10 (mini.iso)
VM: VirtualBox
QT Version: 5.12

**Comment by beanpole135** [comment]
You need the private development header files for the Qt5 theme support module. Typically this is distributed as an optional Qt5 package, or as part of the "-dev" or "-devel" subpackage, depending on how your OS packages the Qt libraries.

The Lumina theme engine was originally a fork of the qt5ct utility back in the day - so you might want to look at the qt5ct package on Ubuntu to see if there are any special packages they bring in to build that as well: https://packages.ubuntu.com/eoan/qt5ct

**Comment by KaiLyons** [comment]
I found the issue, I missed one of the dependencies
