### ISSUE TITLE
Master branch fails to build at start

### ISSUE THREAD

**Issue by tomekdev** [lumina-desktop/lumina#726]
I'm unable to build lumina from sources cloned with git from master branch. Running "make" after "qmake PREFIX=/usr" results in immediate error with missing stdlib.h. After running "make INCPATH+="/usr/include/c++/9" the build fails a bit later, complaining about missing "QMenu" header which is present in my system as "/usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QMenu" and is not empty. Might it be possible that there's something wrong with Makefiles ? I'm running Devuan chimaera/ceres (Debian testing with different init system as default)

**Comment by beanpole135** [comment]
You might need to specify the L_QTLIBDIR option when running qmake for your system if it is not one of the known OS profiles.
The output from running qmake should tell you which OS was recognized/used for the build settings, but you can manually override almost everything at the qmake step.

See https://github.com/lumina-desktop/lumina#how-to-build-from-source- for details.

**Comment by beanpole135** [comment]
Sorry, that L_QTLIBDIR option does not exist (problem with going off-of memory):
The full list of variables and how they tie into the OS detection system can be found here: https://github.com/lumina-desktop/lumina/blob/master/src-qt5/OS-detect.pri

**Comment by tomekdev** [comment]
After manually adjusting INCLUDEPATH right after line 29 I was able to successfully build Lumina

**Comment by tomekdev** [comment]
I think this issue might be closed because small modification which might be considered as build configuration fixes problem
