### ISSUE TITLE
Bug in Lumina Screenshot

### ISSUE THREAD

**Issue by hardcodes** [lumina-desktop/lumina#728]
If you select "Entire Session" and a delay of, let' say 7 seconds in the settings and afterwards check the button "Select Area" and take a screenshot,

- the delay is still active and
- the entire session is snapshotted.

**Comment by q5sys** [comment]
First off, are you still having this issue?  Second, can you give me some information as far as what OS/Distro you're on.

**Comment by hardcodes** [comment]
Sorry for the late feedback. I had this issue with trident-os, which means void linux under the hood. But i haven't used it for almost two years because the last updates caused a flickering screen. Many words for saying: I really don't know.
