### ISSUE TITLE
Lumina freezes after login (Trident OS)

### ISSUE THREAD

**Issue by Lyamc** [lumina-desktop/lumina#732]
Steps to reproduce:

1) Install Trident OS choosing the master and musl branches

2) Login after reboot, or just run "start-lumina-desktop" or whatever it's called

Issue:

Lumina is frozen and there is graphical corruption of sorts. Text half rendered, icons sometimes missing, but every time the mouse can be moved, and terminal can be accessed through CTRL ALT F2, F3, etc.

I found that opening a terminal and running "start-lumuna-desktop" allowed me to get into a working desktop.

For fun I entered a terminal and attempted to return by pressing CTRL ALT F2 then CTRL ALT F1. I got the same broken desktop. I tried to do the same thing: open a terminal and run "start-lumuna-desktop" but it still gave me anither broken desktop.

I'll update tomorrow with more info

**Comment by Lyamc** [comment]
Updated the following:

```
libgbm-20.1.8_1: 2020-09-20 16:26 EDT
libglapi-20.1.8_1: 2020-09-20 16:26 EDT
libxatracker-20.1.8_1: 2020-09-20 16:26 EDT
mesa-20.1.8_1: 2020-09-20 16:26 EDT
mesa-dri-20.1.8_1: 2020-09-20 16:26 EDT
```

Rebooted, was able to log in, no problem. I'll reopen this issue if it happens again.

**Comment by Lyamc** [comment]
Nevermind, it was a fluke. I added a keyboard shortcut for the terminal so I was able to open whatever I need

![image](https://user-images.githubusercontent.com/10787681/93721879-db209800-fb60-11ea-9d60-35a860ac4b31.png)

Desktop still borked

**Comment by q5sys** [comment]
As this is a year old... and Trident is being sunset, I'm closing this ticket.  If you are ever able to reproduce this on another distro, please let me know.
