### ISSUE TITLE
seriously... no tiling or snapping binds?

### ISSUE THREAD

**Issue by brightersun99** [lumina-desktop/lumina#735]
I could not believe it at first, but why is there no way to bind tiling, or snapping windows to edges/ or minimizing to keys....? how can i take this desktop seriously if it can't even do that
no one in their right mind wants to use their mouse for anything and everything

i see you already ignored 2 issues for this 2 years ago so i guess you don't want serious users or to be taken seriously

**Comment by brightersun99** [comment]
not that im ever going to use this again after seeing all these red flags

**Comment by q5sys** [comment]
Lumina uses Fluxbox for the window management, there's nothing we can do to change the way Fluxbox deals with windows.  We have discussed forking fluxbox to fix its deficiencies but after digging around in the code Ken decided it was better to write something new instead.  He's been working on a native Window Manager for Lumina, but sometimes life gets in the way, and unfortunately it's taken longer than expected.
