### ISSUE TITLE
Application name consistency

### ISSUE THREAD

**Issue by grahamperrin** [lumina-desktop/lumina#736]
For example: 

* _Archive Manager_ also known as _Lumina Archiver_

Please, can you make the name of the application match what appears in the title bar of the application?

If there are any other application name inconsistencies, please consider addressing those too. 

Thanks. 

----

From <https://github.com/helloSystem/ISO/pull/123>: 

![Archive Manager](https://user-images.githubusercontent.com/192271/106877000-38605480-66d0-11eb-9ee1-e9987358f64b.png)

* it's _Archive Manager_.

**Comment by q5sys** [comment]
Fixed with https://github.com/lumina-desktop/lumina/pull/779
