### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by rubyFeedback** [lumina-desktop/lumina#770]
Could a few screenshots be shown on the main README? Thanks for reading! Feel free to close this issue at any moment in time.

**Comment by q5sys** [comment]
Yes I can move one in, I've added the most recent screenshot to here: https://github.com/lumina-desktop/lumina-themes/blob/master/artwork/screenshots/Screenshot-2021-10-02-15-55-58.png
and we have quite a few here: https://github.com/lumina-desktop/lumina-website/tree/master/hugo-site/static/images

**Comment by q5sys** [comment]
Added with https://github.com/lumina-desktop/lumina/commit/3c207e7d758bce4f62847d10fcc835aac7e9f856
