### ISSUE TITLE
Request to relicense qsudo from BSD 2-Clause to BSD 3-Clause for the Lumina Desktop

### ISSUE THREAD

**Issue by q5sys** [lumina-desktop/lumina#776]
I'm reaching out to all of you because you're in the commit history of the qsudo project that was originally under the TrueOS Project but is now under Project-Trident.  As Project Trident is shutting down next spring, I'm wanting to bring qsudo directly into the Lumina source tree. 

Currently:

> qsudo is licensed under the BSD 2-Clause
> Lumina is licensed under the BSD 3-Clause

To each of the contributors, do you consent to relicensing your contributions to qsudo to BSD 3-Clause from the point of the [this commit](https://github.com/lumina-desktop/lumina/commit/ee849194b652c7615e239419219ebc85c733437d) forward.  
qsudo itself will live on as its own unique project as a unique repo under my account once the Project-Trident Github Org is shut down.  That repo will remain BSD 2-Clause, to not cause any problems for forks made previously or that may be made in the future.  This request is only to bring these source into Lumina under BSD 3-Clause.

Relicensing requires the consent of each contributor regarding their code contributions.  
If you do not wish to consent, that's you're choice.  If that's the case I will then have to replace your contributions to proceed.
Thanks for taking the time to respond.

- [x] @beanpole135 
- [x] @Mrt134 
- [x] @ZackaryWelch 
- [x] @kmoore134 
- [x] @dmulalic 
- [x] @pkgdemon

**Comment by beanpole135** [comment]
I am fine with it. No "real" difference between 2-Clause and 3-Clause in practical use.

**Comment by ZackaryWelch** [comment]
I consent

**Comment by q5sys** [comment]
> I am fine with it. No "real" difference between 2-Clause and 3-Clause in practical use.

Yea I agree.  No "Real" difference in practical use except to the lawyers and the license trolls.  I'd rather avoid ever running into "that guy" who decides that they're bored and want to cause trouble.  And since everything else is BSD-3... why not just make it all the same.

**Comment by dmulalic** [comment]
Fine with me.

**Comment by pkgdemon** [comment]
Fine with me

**Comment by kmoore134** [comment]
Fine here!

**Comment by q5sys** [comment]
Closing issue as all have consented. This work will be included with the 1.6.2 release of Lumina
