### ISSUE TITLE
Changing Window Theme doesn't work in 1.6.1

### ISSUE THREAD

**Issue by outpaddling** [lumina-desktop/lumina#787]
Changing Window Theme under Window Manager has no effect, even after logging out and back in.
FreeBSD 13.0 work-in-progress port, not yet committed:
https://github.com/lbartoletti/freebsd-ports/tree/lumina-1.6.1 (port maintainer's original)
https://github.com/outpaddling/freebsd-ports-wip (my copy, currently identical)
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259965

I haven't found any other regressions so far.  Nice work on the release...

**Comment by q5sys** [comment]
Interesting.  No code in the Theme manager or lumina-config have changed that I recall.  I'll need to make a FreeBSD 13 install to see if I can determine why its misbehaving

**Comment by q5sys** [comment]
This should fix this: https://github.com/lumina-desktop/lumina/commit/6761adcb603a148b40bc6697de1660a6e9f5e949

**Comment by outpaddling** [comment]
Thanks, I'll import this to my WIP port and retest.

**Comment by outpaddling** [comment]
It does, and also fixes the slow settings resize.
