### ISSUE TITLE
Regarding commit 31d6a38

### ISSUE THREAD

**Issue by karlgrose** [lumina-desktop/lumina#798]
Sorry for the confusion about my previous comment on the typo in lumina-sudo.pro; your [last commit](https://github.com/lumina-desktop/lumina/commit/31d6a387c18118de80b65f4bd5fe1ad85b5d3902):
```
TRANSLATIONS =  i18n/lum_udo_af.ts \
```
is still missing the "s" in \_sudo\_:
```
TRANSLATIONS =  i18n/lum_sudo_af.ts \
```
Thanks again for reviving the Lumina project: As a long-time user, I hope it works out well.

**Comment by q5sys** [comment]
I guess I need to disassemble my keyboard and clean it out. :P 
https://github.com/lumina-desktop/lumina/commit/bdbdacc7818c95dac138331be33d061a208da912
