### ISSUE TITLE
Cannot prompt sudo

### ISSUE THREAD

**Issue by mdesalvo** [lumina-desktop/lumina#807]
It seems not possible to have a graphical prompt for sudo credentials when launching an application requiring it (e.g: synaptic). The application simply won't launch. Environment is lumina 1.6.2 on Xubuntu Focal 20.04 LTS.

**Comment by q5sys** [comment]
Since you closed this, did you figure this out? If so I'd like to know what the issue is so I can document it for other users in case they run into it.
